CREATE TABLE public.user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_user_account_username CHECK (
        username = btrim(username) AND username <> '' AND position('@' IN username) = 0
    ),
    CONSTRAINT ck_user_account_email CHECK (
        email = btrim(email) AND email <> ''
    ),
    CONSTRAINT ck_user_account_nickname CHECK (
        nickname IS NULL OR (nickname = btrim(nickname) AND nickname <> '')
    ),
    CONSTRAINT ck_user_account_role CHECK (role IN ('ADMIN', 'EDITOR', 'USER'))
);

CREATE UNIQUE INDEX uk_user_account_username_lower ON public.user_account (lower(username));
CREATE UNIQUE INDEX uk_user_account_email_lower ON public.user_account (lower(email));

COMMENT ON TABLE public.user_account IS '用户账号表：存储管理员、编辑和普通用户的登录信息';
COMMENT ON COLUMN public.user_account.id IS '用户账号 ID';
COMMENT ON COLUMN public.user_account.username IS '登录用户名，不允许使用邮箱格式';
COMMENT ON COLUMN public.user_account.email IS '登录邮箱';
COMMENT ON COLUMN public.user_account.password_hash IS '密码哈希值，不存储明文密码';
COMMENT ON COLUMN public.user_account.nickname IS '展示昵称，可为空且无需唯一';
COMMENT ON COLUMN public.user_account.role IS '账号角色：ADMIN、EDITOR、USER';
COMMENT ON COLUMN public.user_account.enabled IS '账号是否启用';
COMMENT ON COLUMN public.user_account.email_verified_at IS '邮箱验证完成时间，未验证时为空';
COMMENT ON COLUMN public.user_account.created_at IS '记录创建时间';
COMMENT ON COLUMN public.user_account.updated_at IS '记录最后更新时间';
